version: '3.7'

services:
##### Conteneur Evian #####
  #evian:
  #  image: tomap74/evian
  #  ports:
  #    - 8083:80
  #  volumes:
  #    - ./index.html:/usr/share/nginx/html

##### Conteneur DHCP #####
  dhcp:
    image: sirferdek/isc-dhcp-server
    restart: always
    #ports:
    #  - "67/udp"
    volumes:
      #- /var/lib/dhcp:/var/lib/
      - ./dhcpd.conf:/etc/dhcp/dhcpd.conf
    network_mode: "host"

##### Conteneurs LDAP #####
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=tomscop
      - LDAP_DOMAIN=tomscop.org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      #- LDAP_BASE_DN=""
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=tomscop.org.ca.crt
      #- LDAP_READONLY_USER=true
      #- LDAP_READONLY_USER_USERNAME=user-ro
      #- LDAP_READONLY_USER_PASSWORD=ro_pass

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "3333:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap

##### Conteneur LOGS #####
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./syslog.conf:/etc/syslog-ng/syslog-ng.conf
      - ./logs:/var/log #optional
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped

##### Conteneur PROXY #####
  squid:
    image: ubuntu/squid
    ports:
      - 3128:3128
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords

##### Conteneurs MATOMO (stats) + db.env + matomo.conf #####
  db:
    image: mariadb:10.8
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tom
    ports:
      - 3306:3306
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
      #- ./matomo-config:/var/www/html/config:rw
      #- ./matomo-logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8082:80

##### Conteneu DNS #####
  dns:
    image: ubuntu/bind9
    ports:
      - 192.168.1.128:53:53/udp
    volumes:
      - ./named.conf:/etc/bind/named.conf
      - ./bind:/var/lib/bind

##### Conteneur ZABBIX #####
  zabbix:
    image: zabbix/zabbix-server-mysql
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=tom
      - MYSQL_PASSWORD=tom
    env_file:
      - ./db.env
    depends_on:
      - db

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    env_file:
      - ./db.env
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_USER=tom
      - MYSQL_PASSWORD=tom
      - ZBX_SERVER_HOST=zabbix
    depends_on:
      - db
      - zabbix

##### Conteneur WIREGUARD #####
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SERVERURL=192.168.1.128
      - SERVERPORT=51820
      - PEERS=PC,TEL,PCPRO
      - PEERDNS=auto
      #- INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    restart: unless-stopped

##### Conteneur WIRESHARK #####
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./wireshark-config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped

##### Conteneur ZAP #####
  zap:
    image: owasp/zap2docker-stable
    command: 'zap-webswing.sh'
    ports:
      - 8080:8080
      - 8090:8090

##### Conteneur PORTAINER #####
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000


  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/aptalca/appdata/heimdall:/config
    restart: unless-stopped
    
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=tomscop.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=266564b5-8761-413a-bdb3-2692ff482b70
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

volumes:
  db:
  matomo:
